'\" t
.\" Man page for `aura`
.\" Written by Colin Woodbury <colin@fosskers.ca>
.
.TH aura 8 "2024 July" "Aura" "Aura"
.
.de SAMPLE      \" Indented example - on its own paragraph.
.  P
.  RS
.  EX
..
.de ESAMPLE     \" End of Indented example.
.  EE
.  RE
..
.de RSAMPLE     \" Relative sample - even more indented example.
.  RS
.  SAMPLE
..
.de ERSAMPLE    \" End of Relative sample.
.  ESAMPLE
.  RE
..
.
.ds ellipsis \&.\|.\|.\&
.\" Format repeatable parameter (1 or more) with ellipsis.
.ds multi                 \fI\\$1\fP\fR\\ \\*[ellipsis]\fP
.\" Format optional repeatable parameter (0 or more)
.\" with ellipsis and square brackets.
.ds multi-optional \fR[\fP\fI\\$1\fP\fR\\ \\*[ellipsis]]\fP
.ds packages          \\*[multi          packages]
.ds packages-optional \\*[multi-optional packages]
.
.SH NAME
.
aura \- A package manager for Arch Linux and the AUR
.
.SH SYNOPSIS
.
.SY aura
.I OPERATION
\*[multi-optional OPTIONS]
\*[multi-optional targets]
.YS
.
.SH DESCRIPTION
.
.B aura
is a multilingual package manager for Arch Linux.
.
It connects to both the official Arch repositories and to the
Arch User Repositories (AUR),
allowing easy control of all packages on an Arch system.
.
Aura allows
.I all
pacman operations and provides
.I new
custom ones for dealing with AUR packages.
.
.P
Unlike pacman, it is never necessary to prefix aura with sudo. Aura is
internally aware of when sudo is necessary and will prompt the user.
.
.P
Commands below labeled (Pacman) are wrapped Pacman commands and are not
documented further here. See \fBman pacman\fR for those.
.
.P
This document is strictly a description of Aura's command-line interface. For
in-depth usage examples and more detailed discussions of various system
management tasks, see \fBinfo aura\fR.
.
.SH OPERATIONS
.
.TP
.BR \-A ", " \-\-aursync ", " aur " \*[packages-optional]"
.
Perform actions involving the
.BR A UR.
.
Default action installs packages from the AUR.
.
After building, the built
.I *.pkg.tar.xz
file is moved to the package cache and installed from there.
.
This allows for easy AUR package downgrading.
.
.IP
Packages are built within a local directory as the user who invoked Aura.
However, when Aura is run as the \fBroot\fR user, actual package building will
occur as the \fBnobody\fR user within \fB/tmp\fR. See \fB\-\-build\fR and
\fB\-\-builduser\fR for how to modify this behaviour.
.
.TP
.BR -B ", " \-\-backup ", " backup
.
Manage the saving and restoring of the global package state.
.
Default action stores a record of all currently installed packages and their
versions.
.
.TP
.BR -C ", " \-\-cache ", " cache " \*[packages-optional]"
.
Perform actions involving the package
.BR C ache.
.
Default action downgrades specified
.IR packages .
.
.IP
This process is interactive, allowing the user to choose from any previous
version they have available in the package cache.
.
.TP
.BR -D ", " \-\-database ", " database " \*[packages-optional]"
.
(Pacman) Operate on the package database.
.
.TP
.BR \-F ", " \-\-files ", " files " \*[packages-optional]"
.
(Pacman) Query the files database.
.
.TP
.BR \-L ", " \-\-viewlog ", " log
.
Perform actions involving the pacman
.BR L ogfile.
.
Default action opens the log for read-only viewing.
.
.TP
.BR \-O ", " \-\-orphans ", " orphans " \*[packages-optional]"
.
Perform actions involving
.BR O rphan
packages.
.
Default action is to list the current orphans.
.
.IP
Orphan packages are packages installed as dependencies,
but are no longer required by any other package.
.
.TP
.BR \-Q ", " \-\-query ", " query " \*[packages-optional]"
.
(Pacman) Query the package database.
.
.TP
.BR \-R ", " \-\-remove ", " remove " \*[packages-optional]"
.
(Pacman) Remove packages from the system.
.
.TP
.BR \-S ", " \-\-sync ", " sync " \*[packages-optional]"
.
(Pacman) Synchronize official packages.
.
.TP
.BR \-U ", " \-\-upgrade ", " upgrade " \*[packages-optional]"
.
(Pacman) Upgrade or add packages to the system.
.
.TP
.BR \-V ", " \-\-version
.
Print Aura's current version number.
.
.TP
.BR check
.
Validate your system.
.
.TP
.BR conf
.
View various configuration settings and files. The default action displays all
currently loaded settings as a pretty-printed Rust structure.
.
.IP
Detailed information involving Aura's configuration can be found in the Aura
Guide via \fBinfo aura\fR under the heading \fBConfiguration\fR.
.
.TP
.BR deps
.
Display a dependency graph of given packages. Useful for identifying why a
certain package exists on your system. Outputs a \fB.png\fR file to the current
directory by default, but with \fB\-\-open\fR will output to \fB/tmp\fR and open
the image in the default viewer instead.
.
.IP
If the image isn't opening in the viewer you prefer, consider altering it in
\fI~/.config/mimeapps.list\fR. For instance:
.
.RSAMPLE
[Default Applications]
image/png=swayimg.desktop
.ERSAMPLE
.
.IP
The available \fB.desktop\fR entries can be found in \fI/usr/share/applications/\fR.
.
.TP
.BR free
.
View the state of Free Software installed on the system. This displays a list of
packages that have non-FOSS or otherwise unknown licenses. For the purposes of
this command, "FOSS License" means anything which has been approved by both the
FSF and the OSI.
.
.TP
.BR stats
.
View statistics about your machine or about Aura itself. The default action
displays various environment values and directory sizes relevant to Aura.
.
.TP
.BR thanks
.
The people behind Aura.
.
.SH AUR SYNC OPTIONS (\fR\-A\fP)
.
.TP
.BR \-a ", " \-\-delmakedeps
.
Uninstalls build dependencies that are no longer required after installing the
main package.
.
This prevents the creation of orphan packages.
.
Also note that while the package itself will be uninstalled,
its package file will remain in the cache.
.
.TP
.BR \-c ", " \-\-clean
.
After a package's tarball has been built and copied to the package cache,
delete its build directory immediately.
.
.TP
.BR \-i ", " \-\-info " \*[packages]"
.
View information about AUR
.IR packages .
.
.TP
.BR \-o ", " \-\-open " \*[packages]"
.
Open the given package's AUR page in a browser.
.
.TP
.BR \-p ", " \-\-pkgbuild " \*[packages]"
.
View PKGBUILDs of AUR
.IR packages .
.
Use this before installing new packages to confirm that the build scripts
aren't doing anything fishy.
.
.TP
.BR \-s ", " \-\-search " \*[multi word]"
.
Search the AUR for packages containing
.IR word s
(not regex) in their names or descriptions.
.
Multiple terms will narrow down the search.
.
Results are sorted by votes.
.
Suboptions:
.
.RS
.
.  TP
.  B \-\-abc
.
Sorts results alphabetically.
.
.  TP
.  BR \-\-limit =\fIN\fR
.
Only show the first
.I N
results.
.
.  TP
.  BR \-q ", " \-\-quiet
.
Only print matching package names.
.
.  TP
.  BR \-r ", " \-\-reverse
.
Reverse the order of the search results.
.
.RE
.
.TP
.BR \-u ", " \-\-sysupgrade
.
Upgrade all installed AUR packages.
.
Suboptions:
.
.RS
.
.  TP
.  BR \-d ", " \-\-dryrun
.
Show available upgrades, but do not perform them.
.
.  TP
.  BR \-k ", " \-\-diff
.
View diffs of PKGBUILDs before building.
.
.  TP
.  BR \-\-ignore \ \fIpackage\fR
.
Don't consider a given package for upgrades. Can be passed more than once. See also the \fBignores\fR list in Aura's configuration to ensure that certain packages are never upgraded.
.
.  TP
.  BR \-\-git
.
Rebuild all git/svn/hg/etc. packages as well.
.
.RE
.
.TP
.BR \-v ", " \-\-provides \ \fIpackage\fR
.
Search the AUR for packages that "provide" some package identity. The same
suboptions available for \fI\-s\fR also apply here. Example:
.
.RSAMPLE
aura -Av gcc
.ERSAMPLE
.
.IP
This would yield a list of packages that "are" gcc for the purposes of
dependency resolution.
.
.TP
.BR \-w ", " \-\-clone " \*[packages]"
.
Clone the repository of the given package(s).
.
.
.TP
.BR \-y ", " \-\-refresh
.
Pull the latest changes for every local copy of an AUR package.
.
.TP
.B \-\-asdeps
.
Give installed packages the "non-explicit" status.
.
.TP
.BI \-\-build " path"
.
Specify build
.I path
when building AUR packages.
.
.TP
.BI \-\-builduser " user"
.
Specify the
.I user
to build packages as.
.
This can be useful when logged in as root and a build user is available.
.
.TP
.B \-\-hotedit
.
Before building, prompt the user if they wish to view/edit the
.IR PKGBUILD ,
as well as any
.IR .install " or " .patch
files.
.
However, research into packages (and by extension, their PKGBUILDs) should be
done by the user before any building occurs.
.
Please use
.BR \-Ai " and " \-Ap
for this,
as they will be much faster at presenting information than searching the AUR
website manually.
.
.TP
.B \-\-nocheck
.
(Makepkg) Do not consider checkdeps when resolving dependencies, nor run the
check() function of the PKGBUILD.
.
.TP
.BR \-\-noconfirm
.
Do not ask for any confirmation.
.
.TP
.B \-\-shellcheck
.
Run shellcheck on PKGBUILDs before building.
.
.TP
.B \-\-skipdepcheck
.
Perform no dependency solving.
.
Consider this when using
.B \-\-hotedit
to avoid building annoying dependencies that aren't necessary for your special
use-case.
.
.TP
.B \-\-skipinteg
.
(Makepkg) Do not perform any verification checks on source files.
.
.TP
.B \-\-skippgpcheck
.
(Makepkg) Do not verify associated PGP signatures.
.
.SH GLOBAL PACKAGE STATE OPTIONS (\fR\-B\fP)
.
.TP
.BR \-c ", " \-\-clean \c
.I " states-to-retain "
.
Retains a given number of the most recently saved package states and removes the
rest.
.
.TP
.BR \-l ", " \-\-list
.
Show all saved package state filenames.
.
.TP
.BR \-r ", " \-\-restore
.
Restores a record kept with
.BR \-B .
.
Attempts to downgrade any packages that were upgraded since the chosen save.
.
Will remove any that weren't installed at the time.
.
.SH PACKAGE CACHE OPTIONS (\fR\-C\fP)
.
.TP
.BR \-b ", " \-\-backup \c
.I " path "
.
Backup the package cache to a given directory.
.
The given directory must already exist.
.
During copying, progress will be shown.
.
If the copy takes too long,
you may want to reduce the number of older versions of each package by using
.BR \-Cc .
.
.TP
.BR \-c ", " \-\-clean \c
.I " versions-to-retain "
.
Retains a given number of package versions for each package,
and deletes the rest from the package cache.
.
Count is made from the most recent version, so using:
.
.RSAMPLE
aura -Cc 3
.ERSAMPLE
.
.IP
would save the three most recent versions of each package file.
.
Giving the number 0 as an argument is identical to
.BR \-Scc .
.
.TP
.BR \-i ", " \-\-info " \*[packages]"
.
Look up specific packages for into on their cache entries.
.
.TP
.BR \-l ", " \-\-list
.
Print the contents of the package cache.
.TP
.BR \-m ", " \-\-missing
.
Display packages that don't have a tarball in the cache.
.
.TP
.BR \-n ", " \-\-notsaved
.
Delete tarballs which are not saved in any package record (a la
.BR \-B ).
.
.TP
.BR \-s ", " \-\-search \c
.I " term "
.
Search the package cache via a verbatim search term.
.
.TP
.BR \-t ", " \-\-invalid
.
Delete invalid tarballs from the cache. Here "invalid" means "can't be opened by ALPM".
.
.TP
.BR \-y ", " \-\-refresh
.
Download tarballs of installed packages that are missing from the cache. This is
important for interaction with \fB\-Br\fR, which can't function if expected
tarballs are missing. Use \fBaura check\fR to confirm the status of both the
cache and the saved snapshots.
.
.SH LOGFILE OPTIONS (\fR\-L\fP)
.
.TP
.BR \-a ", " \-\-after \ \fIYYYY-MM-DD\fR
.
When used with \fI\-L\fR, only display log entries from after the given date.
.
.TP
.BR \-b ", " \-\-before \ \fIYYYY-MM-DD\fR
.
When used with \fI\-L\fR, only display log entries from before the given date.
.
.TP
.BR \-i ", " \-\-info " \*[packages]"
.
Displays install/upgrade history for given
.IR packages .
.
Under the \(lqRecent Actions\(rq section,
only the last five entries will be displayed.
.
If there are less than five actions ever performed with the package,
what is available will be printed.
.
.TP
.BR \-s ", " \-\-search \c
.I " term "
.
Search the pacman log file via a search term.
.
Useful for singling out any and all actions performed on a package.
.
.SH ORPHAN PACKAGE OPTIONS (\fR\-O\fP)
.
.TP
.BR \-a ", " \-\-adopt " \*[packages]"
.
Mark
.I packages
as being explicitly installed (i.e.\& it's not a dependency).
.
.TP
.BR \-e ", " \-\-elderly
.
Display all explicitly installed, top-level packages. If you notice something
that you don't remember installing or perhaps don't need anymore, you can then
uninstall it.
.
.TP
.BR \-j ", " \-\-abandon
.
Uninstall all orphan packages.
.
.SH CONFIGURATION (conf)
.
.TP
.BR \-a ", " \-\-aura
.
View the contents of ~/.config/aura/config.toml.
.
.TP
.BR \-g ", " \-\-gen
.
Output your current, full Aura config as legal TOML. After your first install,
you should run the following:
.
.RSAMPLE
aura conf --gen > ~/.config/aura/config.toml
.ERSAMPLE
.
.TP
.BR \-m ", " \-\-makepkg
.
View the Makepkg configuration file. This respects the value of \fBMAKEPKG_CONF\fR.
.TP
.BR \-p ", " \-\-pacman
.
View the Pacman configuration file.
.
.SH DEPENDENCY ANALYSIS (deps)
.
.TP
.BR \-l ", " \-\-limit =\fIN\fR
.
The number of layers up or down to allow. Without this, you may notice that
calls to \fBdeps\fR for certain packages take a long time, or produce a massive,
unusable image.
.
.TP
.BR \-o ", " \-\-optional
.
Include optional dependencies. These will be referenced with a dotted line in
the image.
.
.TP
.BR \-r ", " \-\-reverse
.
The opposite of normal operation, this displays packages that depend on the
given arguments. Good for answering questions like "What depends on foo?"
.
.TP
.BR \-\-open
.
Open the output image automatically.
.TP
.BR \-\-raw
.
Print the raw DOT output instead of producing an image file.
.
.SH FREE SOFTWARE LICENSES (free)
.
.TP
.BR \-\-copyleft
.
Consider only Copyleft licenses.
.
.TP
.BR \-\-lenient
.
Allow FOSS-derived custom licenses.
.
.SH SYSTEM STATISTICS (stats)
.
.TP
.BR \-g ", " \-\-groups
.
View all installed package groups.
.
.TP
.BR \-\-heavy
.
View the Top 10 heaviest installed packages.
.
.TP
.BR \-l ", " \-\-lang
.
View Aura's localisation statistics. The language codes displayed here can be
used in the \fBlanguage\fR field of Aura's configuration.
.
.SH OTHER GLOBAL OPTIONS
.
.TP
.BR \-h ", " \-\-help
.
Display basic help. Can be used with any top-level Operation.
.
.TP
.B \-\-log-level \fIlevel\fR
.
Minimum level of Aura log messages to display. Available values are \fBdebug\fR,
\fBinfo\fR, \fBwarn\fR, and \fBerror\fR.
.
.SH LANGUAGE OPTIONS
.
Aura is available in multiple languages.
.
As options, they can be used with either their English names or their real
names written in their native characters.
.
The available languages are, in option form:
.
.P
.TS \" Tab-separated
l l.
\fB\-\-arabic\fP
\fB\-\-croatian\fP	\fB\-\-hrvatski\fP
\fB\-\-czech\fP	\fB\-\-čeština\fP
\fB\-\-dutch\fP	\fB\-\-nederlands\fP
\fB\-\-english\fP	(default)
\fB\-\-esperanto\fP
\fB\-\-french\fP	\fB\-\-français\fP
\fB\-\-german\fP	\fB\-\-deutsch\fP
\fB\-\-hindi\fP	\fB\-\-हिंदी\fP
\fB\-\-indonesian\fP
\fB\-\-italian\fP	\fB\-\-italiano\fP
\fB\-\-japanese\fP	\fB\-\-日本語\fP
\fB\-\-korean\fP	\fB\-\-한국어\fP
\fB\-\-norwegian\fP	\fB\-\-norsk\fP
\fB\-\-polish\fP	\fB\-\-polski\fP
\fB\-\-portuguese\fP	\fB\-\-português\fP
\fB\-\-romanian\fP	\fB\-\-română\fP
\fB\-\-russian\fP	\fB\-\-русский\fP
\fB\-\-serbian\fP	\fB\-\-српски\fP
\fB\-\-simplified-chinese\fP	\fB\-\-简体字\fP
\fB\-\-spanish\fP	\fB\-\-español\fP
\fB\-\-swedish\fP	\fB\-\-svenska\fP
\fB\-\-turkish\fP
\fB\-\-ukranian\fP	\fB\-\-українська\fP
\fB\-\-vietnamese\fP
.TE
.
.P
Note that these flags are not the expected way to alter Aura's language for
normal usage. If your locale is set to something that Aura recognizes, it will
automatically alter its output language. Otherwise, you're able to set the
\fBlanguage\fR field within configuration. The available language codes can be
viewed in the output of \fBaura stats --lang\fR.
.
.P
See the \fBLocalisation\fR topic within \fBinfo aura\fR for instructions on
adding a new language to Aura.
.
.SH PRO TIPS
.
.IP \(bu 2n
.
After first installation, run:
.
.RSAMPLE
aura conf --gen > ~/.config/aura/config.toml
.ERSAMPLE
.
.IP
to generate a configuration file that you can customise.
.
.IP \(bu 2n
.
Use \fBaura check\fR to keep an eye on some aspects of the health of your
system.
.
.IP \(bu 2n
.
If you build a package and then choose not to install it,
the built package file will still be moved to the cache.
You can then install it whenever you want with
.BR \-C .
.
.IP \(bu 2n
.
Research packages using
.BR \-Ai \ ( \-\-info )
and
.BR \-Ap \ ( \-\-pkgbuild )!
.
.IP \(bu 2n
.
When upgrading, use
.B \-Akua
instead of just
.BR \-Au .
.
This will remove makedeps, as well as show PKGBUILD diffs before building. The
effects of \fB\-k\fR and \fB\-a\fR can however be enabled permanently in Aura's
config.
.
.SH SEE ALSO
.
.BR pacman (8),
.BR pacman.conf (5),
.BR makepkg (8)
.
.P
Apart from the various flags described here, the Aura Manual is available via
.B info aura
and contains more detailed usage information.
.
.SH BUGS
.
It is not recommended to install non-AUR packages with pacman or aura.
.
Aura will assume they are AUR packages during a
.B \-Au
and attempt to upgrade them.
.
If a name collision occurs (that is, if there is a legitimate AUR package with
the same name as the one you installed) previous installations could be
overwritten.
.
.P
You may occasionally notice that Aura doesn't detect new package versions
immediately after they are updated on the AUR. This is because Aura fetches
package metadata from a dedicated server, not the AUR directly. The dedicated
server refreshes its database every hour, so in these cases we ask you to be
patient.
.
.SH AUTHOR
.
Colin Woodbury <colin@fosskers.ca>
.
.SH CONTRIBUTORS
.
.TS \" Tab-separated
l .
Chris Warrick
Brayden Banks
Denis Kasak
Edwin Marshall
Jimmy Brisson
Kyle Raftogianis
Nicholas Clarke
.TE
.
.SH TRANSLATORS
.
.TS \" Tab-separated
c l .
Polish	Chris Warrick and Michał Kurek
Croatian	Denis Kasak and "stranac"
Swedish	Fredrik Haikarainen and Daniel Beecham
German	Lukas Niederbremer
Spanish	Alejandro Gómez, Sergio Conde, and Max Ferrer
Portuguese	Henry Kupty, Thiago Perrotta, and Wagner Amaral
French	Ma Jiehong and Fabien Dubosson
Russian	Kyrylo Silin and Alexey Kotlyarov
Italian	Bob Valantin and Cristian Tentella
Serbian	Filip Brcic
Norwegian	"chinatsun"
Indonesian	"pak tua Greg"
Chinese	Kai Zhang
Japanese	Onoue Takuro and Colin Woodbury
Esperanto	Zachary Matthews
Dutch	Joris Blanken and Heimen Stoffels
Turkish	Cihan Alkan
Arabic	"Array in a Matrix"
Ukrainian	Andriy Cherniy
Romanian	"90" and "benone"
Vietnamese	"Kritiqual"
Czech	Daniel Rosel
Korean	"Nioden"
Hindi	"@yozachar"
.TE
