.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH aura 1  "aura 4.0.0-alpha1" 
.SH NAME
aura \- Install and manage Arch Linux and AUR packages
.SH SYNOPSIS
\fBaura\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fB\-\-english\fR] [\fB\-\-japanese\fR] [\fB\-\-german\fR] [\fB\-\-log\-level\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Install and manage Arch Linux and AUR packages
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information
.TP
\fB\-\-english\fR
Output in English
.TP
\fB\-\-japanese\fR
Output in Japanese (alias: 日本語)
.TP
\fB\-\-german\fR
Output in German (alias: deutsch)
.TP
\fB\-\-log\-level\fR=\fIlevel\fR
Minimum level of Aura log messages to display
.SH SUBCOMMANDS
.TP
aura\-database(1)
Operate on the package database
.TP
aura\-files(1)
Query the files database
.TP
aura\-query(1)
Query the package database
.TP
aura\-remove(1)
Remove packages from the system
.TP
aura\-sync(1)
Synchronize official packages
.TP
aura\-dep\-test(1)
Check if given dependencies are satisfied
.TP
aura\-upgrade(1)
Upgrade or add packages to the system
.TP
aura\-aur(1)
Synchronize AUR packages
.TP
aura\-backup(1)
Save and restore the global package state
.TP
aura\-cache(1)
Manage the package cache
.TP
aura\-log(1)
View the Pacman/ALPM log
.TP
aura\-orphans(1)
Handle orphan packages
.TP
aura\-check(1)
Validate your system
.TP
aura\-conf(1)
View various configuration settings and files
.TP
aura\-deps(1)
Output a dependency graph in DOT format
.TP
aura\-open(1)
Open various webpages related to Aura
.TP
aura\-stats(1)
View statistics about your machine or about Aura itself
.SH VERSION
v4.0.0\-alpha1
.SH AUTHORS
Colin Woodbury <colin@fosskers.ca>
