.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH aura 1  "aura " 
.SH NAME
aura \- Query the package database
.SH SYNOPSIS
\fBaura\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-c\fR|\fB\-\-changelog\fR] [\fB\-d\fR|\fB\-\-deps\fR] [\fB\-e\fR|\fB\-\-explicit\fR] [\fB\-g\fR|\fB\-\-groups\fR] [\fB\-i\fR|\fB\-\-info\fR] [\fB\-k\fR|\fB\-\-check\fR] [\fB\-l\fR|\fB\-\-list\fR] [\fB\-m\fR|\fB\-\-foreign\fR] [\fB\-n\fR|\fB\-\-native\fR] [\fB\-o\fR|\fB\-\-owns\fR] [\fB\-p\fR|\fB\-\-file\fR] [\fB\-q\fR|\fB\-\-quiet\fR] [\fB\-s\fR|\fB\-\-search\fR] [\fB\-t\fR|\fB\-\-unrequired\fR] [\fB\-u\fR|\fB\-\-upgrades\fR] [\fB\-v\fR|\fB\-\-verbose\fR] [\fB\-\-arch\fR] [\fB\-\-cachedir\fR] [\fB\-\-color\fR] [\fB\-\-config\fR] [\fB\-\-confirm\fR] [\fB\-\-debug\fR] [\fB\-b\fR|\fB\-\-dbpath\fR] [\fB\-\-disable\-download\-timeout\fR] [\fB\-\-gpgdir\fR] [\fB\-\-hookdir\fR] [\fB\-\-logfile\fR] [\fB\-\-noconfirm\fR] [\fB\-\-root\fR] [\fB\-\-sysroot\fR] [\fIPACKAGES\fR] 
.SH DESCRIPTION
Query the package database
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-c\fR, \fB\-\-changelog\fR
View the changelog of a package
.TP
\fB\-d\fR, \fB\-\-deps\fR
List packages installed as dependencies [filter]
.TP
\fB\-e\fR, \fB\-\-explicit\fR
List packages explicitly installed [filter]
.TP
\fB\-g\fR, \fB\-\-groups\fR
View all members of a package group
.TP
\fB\-i\fR, \fB\-\-info\fR
View package information (\-ii for backup files)
.TP
\fB\-k\fR, \fB\-\-check\fR
Check that package files exist (\-kk for file properties)
.TP
\fB\-l\fR, \fB\-\-list\fR
List the files owned by the queried package
.TP
\fB\-m\fR, \fB\-\-foreign\fR
List installed packages not found in sync db(s) [filter]
.TP
\fB\-n\fR, \fB\-\-native\fR
List installed packages only found in sync db(s) [filter]. Print the targets instead of performing the operation
.TP
\fB\-o\fR, \fB\-\-owns\fR=\fIfile\fR
Query the package that owns <file>
.TP
\fB\-p\fR, \fB\-\-file\fR=\fIpackage\fR
Query a package file instead of the database
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Show less information for query and search
.TP
\fB\-s\fR, \fB\-\-search\fR
Search remote repositories for matchings strings
.TP
\fB\-t\fR, \fB\-\-unrequired\fR
List packages not (optionally) required by any package (\-tt to ignore optdepends) [filter]
.TP
\fB\-u\fR, \fB\-\-upgrades\fR
List outdated packages [filter]
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Be verbose
.TP
\fB\-\-arch\fR=\fIARCH\fR
Set an alternate architecture
.TP
\fB\-\-cachedir\fR=\fIpath\fR
Set an alternate package cache location
.TP
\fB\-\-color\fR=\fIwhen\fR
Colorize the output
.TP
\fB\-\-config\fR=\fIpath\fR
Set an alternate Pacman configuration file
.TP
\fB\-\-confirm\fR
Always ask for confirmation
.TP
\fB\-\-debug\fR
Display Pacman debug messages
.TP
\fB\-b\fR, \fB\-\-dbpath\fR=\fIpath\fR
Set an alternate database location
.TP
\fB\-\-disable\-download\-timeout\fR
Use relaxed timeouts for download
.TP
\fB\-\-gpgdir\fR=\fIpath\fR
Set an alternate home directory for GnuPG
.TP
\fB\-\-hookdir\fR=\fIdir\fR
Set an alternate hook location
.TP
\fB\-\-logfile\fR=\fIpath\fR
Set an alternate log file
.TP
\fB\-\-noconfirm\fR
Do not ask for any confirmation
.TP
\fB\-\-root\fR=\fIpath\fR
Set an alternate installation root
.TP
\fB\-\-sysroot\fR
Operate on a mounted guest system (root\-only)
.TP
[\fIPACKAGES\fR]
Packages to query
