.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH aura 1  "aura " 
.SH NAME
aura \- Handle orphan packages
.SH SYNOPSIS
\fBaura\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-a\fR|\fB\-\-adopt\fR] [\fB\-j\fR|\fB\-\-abandon\fR] 
.SH DESCRIPTION
Handle orphan packages
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-a\fR, \fB\-\-adopt\fR=\fIpackages\fR
Mark a package as being explicitly installed
.TP
\fB\-j\fR, \fB\-\-abandon\fR
Uninstall all orphan packages
