.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH aura 1  "aura " 
.SH NAME
aura \- Open various webpages related to Aura
.SH SYNOPSIS
\fBaura\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-d\fR|\fB\-\-docs\fR] [\fB\-r\fR|\fB\-\-repo\fR] [\fB\-b\fR|\fB\-\-bug\fR] [\fB\-a\fR|\fB\-\-aur\fR] 
.SH DESCRIPTION
Open various webpages related to Aura
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-d\fR, \fB\-\-docs\fR
Open the Aura Guide Book
.TP
\fB\-r\fR, \fB\-\-repo\fR
Open Aura\*(Aqs Github repository
.TP
\fB\-b\fR, \fB\-\-bug\fR
File a bug report for Aura
.TP
\fB\-a\fR, \fB\-\-aur\fR
Open Aura\*(Aqs AUR page
