.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH aura 1  "aura " 
.SH NAME
aura \- View statistics about your machine or Aura itself
.SH SYNOPSIS
\fBaura\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-l\fR|\fB\-\-lang\fR] [\fB\-g\fR|\fB\-\-groups\fR] [\fB\-\-heavy\fR] 
.SH DESCRIPTION
View statistics about your machine or Aura itself
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-l\fR, \fB\-\-lang\fR
View Aura\*(Aqs localization statistics
.TP
\fB\-g\fR, \fB\-\-groups\fR
View all installed package groups
.TP
\fB\-\-heavy\fR
View the Top 10 heaviest installed packages
