.\" Man page for `aura`
.\" Written by Colin Woodbury <colingw@gmail.com>

.TH aura 8 "August 2012" "Aura" "Aura Manual"

.\" Disable hyphenation.
.nh

.SH NAME
aura \- A package manager for Arch Linux and the AUR.

.SH SYNOPSIS
\fIaura\fR <operation> [options] [package(s)]

.SH DESCRIPTION
.P
\fIaura\fR is a package manager for Arch Linux written in Haskell.
It connects to both the official Arch repositories and to the Arch User
Repositories (AUR), allowing easy control of all packages on an Arch system.
It allows \fIall\fR pacman operations and provides \fInew\fR custom ones
for dealing with AUR packages. This differs from some other AUR package
managers.
 
.SH OPERATIONS
.P
\-A, \-\-aursync
.RS 4
Perform actions involving the [A]UR. Default action installs packages
from the AUR. During building, makepkg output is \fInot\fR shown 
by default. After building, the built .pkg.tar.xz file is moved
to the package cache and installed from there. This allows for easy 
AUR package downgrading.
.RE 
.P
\-C, \-\-downgrade
.RS 4
Perform actions involving the package [C]ache. Default action downgrades
specified packages. This process is interactive, allowing the user to choose
from any previous version they have available in the package cache.
.RE

.SH AUR SYNC OPTIONS
.P

.SH DOWNGRADE OPTIONS
.P

.SH LOGFILE OPTIONS
.P

.SH SEE ALSO
.P
\fBpacman\fR(8), \fBpacman.conf\fR(5), \fBmakepkg\fR(8)

.SH BUGS
.P

.SH AUTHORS
.P
Colin Woodbury <colingw@gmail.com>
