'\" t
.\" Man page for `aura`
.\" Written by Colin Woodbury <colin@fosskers.ca>
.
.TH aura 8 "2021 January" "Aura" "Aura Manual"
.
.de SAMPLE      \" Indented example - on its own paragraph.
.  P
.  RS
.  EX
..
.de ESAMPLE     \" End of Indented example.
.  EE
.  RE
..
.de RSAMPLE     \" Relative sample - even more indented example.
.  RS
.  SAMPLE
..
.de ERSAMPLE    \" End of Relative sample.
.  ESAMPLE
.  RE
..
.
.SH NAME
.
aura \- package manager utility and AUR helper
.
.SH SYNOPSIS
.
\fIaura\fR <operation> [options] [package(s)]
.
.SH DESCRIPTION
.
\fIaura\fR is a secure, multilingual package manager for Arch Linux written in
Haskell. It connects to both the official Arch repositories and to the Arch User
Repositories (AUR), allowing easy control of all packages on an Arch system.
Aura allows \fIall\fR pacman operations and provides \fInew\fR custom ones for
dealing with AUR packages.
.
.SH OPERATIONS
.
.TP
\fB\-A\fR, \-\-aursync [package(s)]
.
Perform actions involving the [A]UR. Default action installs packages from the
AUR. During building, makepkg output is \fInot\fR shown by default. After
building, the built \fI.pkg.tar.xz\fR file is moved to the package cache and
installed from there. This allows for easy AUR package downgrading.
.
.TP
\fB\-B\fR, \-\-save
.
Manage the saving and restoring of the global package state. Default action
stores a record of all currently installed packages and their versions.
.
.TP
\fB\-C\fR, \-\-downgrade [package(s)]
.
Perform actions involving the package [C]ache. Default action downgrades
specified packages. This process is interactive, allowing the user to choose
from any previous version they have available in the package cache.
.
.TP
\fB\-L\fR, \-\-viewlog
.
Perform actions involving the pacman [L]ogfile.
Default action opens the log for read-only viewing.
.
.TP
\fB\-O\fR, \-\-orphans [package(s)]
.
Perform actions involving [O]rphan packages. Orphan packages are packages
installed as dependencies, but are no longer required by any other package.
Default action is to list the current orphans.
.
.TP
\fB\-P\fR, \-\-analysis <stdin>
.
Perform security analysis of a [P]KGBUILD. Useful for package maintainers and
sysadmins to verify the safety of the PKGBUILD files that they write. To test
any package on the AUR, try the following:
.
.RSAMPLE
aura -Ap <package> | aura -P
.ERSAMPLE
.
.SH AUR SYNC OPTIONS (\fI\-A\fP)
.
.TP
\fB\-a\fR, \-\-delmakedeps
.
Uninstalls build dependencies that are no longer required after installing the
main package. This prevents the creation of orphan packages. Also note that
while the package itself will be uninstalled, its package file will remain in
the cache.
.
.TP
\fB\-c\fR, \-\-clean
.
After a package's tarball has been built and copied to the package cache,
delete its build directory immediately.
.
.TP
\fB\-d\fR, \-\-deps <package(s)>
.
View all the dependencies of a package. This process is recursive for AUR
packages, so all dependencies of dependencies (and so on) will also be shown.
This can aid the pre-install package research process.
.
.TP
\fB\-i\fR, \-\-info <package(s)>
.
View information about a package in the AUR.
.
.TP
\fB\-k\fR, \-\-diff
.
Shows PKGBUILD diffs. When upgrading, using this option will compare the most
and second-most recent PKGBUILDs and output changes in colour.
.
.TP
\fB\-p\fR, \-\-pkgbuild <package(s)>
.
Outputs an AUR package's PKGBUILD. Use this before installing new packages to
confirm that the build scripts aren't doing anything fishy.
.
.TP
\fB\-q\fR, \-\-quiet
.
Display less information about certain aursync operations (this is useful when
processing Aura's output in a script). In particular, search and view
dependencies will only show uncoloured package names.
.
.TP
\fB\-s\fR, \-\-search <word>
.
Search the AUR via a word only (no regex). Results are sorted by vote.
Suboptions:
.
.RS
.
.TP
\fB\-\-abc\fR
Sorts results alphabetically.
.
.TP
\fB\-\-head\=n\fR
Only show the first n results. Default n = 10.
.
.TP
\fB\-\-tail\=n\fR
Only show the last n results.  Default n = 10.
.
.TP
\fB\-r\fR, \fB\-\-both\fR
Show results from the official repos as well.
.
.RE
.
.TP
\fB\-u\fR, \-\-sysupgrade
.
Upgrade all installed AUR packages. \fI\-Au\fR is \fI\-Su\fR for AUR packages.
.
.TP
\fB\-w\fR, \-\-downloadonly <package(s)>
.
Download a package tarball.
.
.TP
\fB\-x\fR, \-\-unsuppress
.
Unsuppress \fImakepkg\fR output during building. By default this output is
suppressed for a more silent install. Note that when this option isn't used,
\fImakepkg\fR output is actually collected and printed if any errors occur.
.
.TP
\fB\-\-json\fP <package(s)>
.
Query the AUR RPC for package info as raw JSON. Good for debugging.
.
.TP
\fB\-\-build\fR <path>
.
Specify build path when building AUR packages. Only the \fIfull\fR path of a
pre-existing directory can be used. Example:
.
.RSAMPLE
aura -A foo --build=/full/path/to/build/location/
.ERSAMPLE
.
.TP
\fB\-\-builduser\fR <username>
.
Specify the user to build packages as. This can be useful when logged in as
root and a build user is available.
.
.TP
\fB\-\-devel\fR
.
When ran with \fI\-Au\fR, adds all development packages to the queue of
packages to upgrade. Devel packages are those pulled directly from online
repositories, via git / mercurial / etc.
.
.TP
\fB\-\-dryrun\fR
.
When ran with \fI\-A\fR or \fI\-Au\fR, update checks, PKGBUILD diffs, and
dependency checks will be performed, but nothing will be built. Also usable
with \fI\-M\fR.
.
.TP
\fB\-\-force\fR
.
Always (re)build the specified packages. Usually Aura will not rebuild packages
whose versions are already available in the local package cache.
.
.TP
\fB\-\-hotedit\fR
.
Prompt the user before building to ask if they wish to view/edit the PKGBUILD,
as well as any .install or .patch files. However, research into packages (and by
extension, their PKGBUILDs) should be done by the user before any building
occurs. Please use \fI\-Ap\fR and \fI\-Ad\fR for this, as they will be much
faster at presenting information than searching the AUR website manually. Note
that, since aura is run through sudo, your local value of $EDITOR may not be
preserved. Run as "sudo \fI\-E\fR aura -A --hotedit ..." to preserve your
environment. To always allow environment variables to be passed, have a look at
the \fIenv_reset\fR and \fIenv_keep\fR options in \fBsudoers\fR(5).
.
.TP
\fB\-\-skipdepcheck\fR
.
Perform no dependency solving. Consider this when using \fI\-\-hotedit\fR to
avoid building annoying dependencies that aren't necessary for your special
use-case.
.
.TP
\fB\-\-vcspath\fP \fI<path>\fP
.
Save the cloned sources of VCS packages (i.e. those that end in \fI*-git\fR, etc.)
in the given location, instead of the default \fI/var/cache/aura/vcs/\fR.
.
.SH GLOBAL PACKAGE STATE OPTIONS (\fI\-B\fP)
.
.TP
\fB\-c\fR, \-\-clean <states-to-retain>
.
Saves a given number of the most recently saved package states and removes the
rest.
.
.TP
\fB\-r\fR, \-\-restore\fR
.
Restores a record kept with \fI\-B\fR. Attempts to downgrade any packages that
were upgraded since the chosen save. Will remove any that weren't installed at
the time.
.
.TP
\fB\-l\fR, \-\-list\fR
.
Show all saved package state filenames.
.
.SH DOWNGRADE OPTIONS (\fI\-C\fP)
.
.TP
\fB\-b\fR, \-\-backup <path>
.
Backup the package cache to a given directory. The given directory must already
exist. During copying, progress will be shown. If the copy takes too long, you
may want to reduce the number of older versions of each package by using
\fI\-Cc\fR.
.
.TP
\fB\-c\fR, \-\-clean <versions-to-retain>
.
Saves a given number of package versions for each package and deletes the rest
from the package cache. Count is made from the most recent version, so using:
.
.RSAMPLE
aura -Cc 3
.ERSAMPLE
.
.IP
would save the three most recent versions of each package file.
Giving the number 0 as an argument is identical to \fI\-Scc\fR.
.
.TP
\fB\-\-notsaved\fP
.
Remove only those package files which are not saved in a package record (a la \fI\-B\fR).
.
.TP
\fB\-s\fR, \-\-search <regex>
.
Search the package cache via a regex. Any package name that matches the regex
will be output as\-is.
.
.SH LOGFILE OPTIONS (\fI\-L\fP)
.
.TP
\fB\-i\fR, \-\-info <package(s)>
.
Displays install / upgrade history for a given package. Under the `Recent
Actions` section, only the last five entries will be displayed. If there are
less than five actions ever performed with the package, what is available will
be printed.
.
.TP
\fB\-s\fR, \-\-search <regex>
.
Search the pacman log file via a regex. Useful for singling out any and all
actions performed on a package.
.
.SH ORPHAN PACKAGE OPTIONS (\fI\-O\fP)
.
.TP
\fB\-a\fR, \-\-adopt <package(s)>
.
Mark a package as being explicitly installed (i.e. it's not a dependency).
.
.TP
\fB\-j\fR, \-\-abandon
.
Uninstall all orphan packages.
.
.SH ANALYSIS OPTIONS (\fI\-P\fP)
.
.TP
\fB\-f\fR, \-\-file <path>
.
Analyse a given PKGBUILD.
.
.TP
\fB\-d\fR, \-\-dir <path>
.
Analyse a PKGBUILD found in the specified directory.
.
.TP
\fB\-a\fR, \-\-audit
.
Analyse the PKGBUILDs of all locally installed AUR packages.
.
.SH PACMAN / AURA DUAL FUNCTIONALITY OPTIONS
.
.TP
\-\-noconfirm
.
Never ask for any Aura or Pacman confirmation. Any time a prompt would
appear, say before building or installation, it is assumed the user
answered in whatever way would progress the program.
.
.TP
\-\-needed
.
Don't rebuild/reinstall packages that are already up to date.
.
.TP
\-\-debug
.
View some handy debugging information.
.
.TP
\-\-color [mode]
.
Whether or not to colour output text. Without this flag, both Aura and Pacman
will attempt to colour text if the terminal allows it. Otherwise, you can pass
\fInever\fR or \fIalways\fR to be specific about your wants.
.
.TP
\-\-overwrite <glob>
.
If there are file conflicts during installation, overwrite conflicting files
that match the given glob pattern.
.
.SH EXPOSED MAKEPKG OPTIONS
.
.TP
\-\-ignorearch
.
Ignores processor architecture when building packages.
.
.TP
\-\-allsource
.
Creates a \fI.src\fR file containing all the downloaded sources (code, etc) and
stores it at \fI/var/cache/aura/src/\fR. To change the location where sources
are stored, use the \fI\-\-allsourcepath\fR flag.
.
.TP
\-\-skipinteg
.
Skip package source integrity checks.
.
.TP
\-\-skippgpcheck
.
Skip all PGP checks.
.
.SH LANGUAGE OPTIONS
.
Aura is available in multiple languages. As options, they can be used with
either their English names or their real names written in their native
characters. The available languages are, in option form:
.
.TS \" Tab-separated
l l.
\fB\-\-english\fP	(default)
\fB\-\-japanese\fP	\fB\-\-日本語\fP
\fB\-\-polish\fP	\fB\-\-polski\fP
\fB\-\-croatian\fP	\fB\-\-hrvatski\fP
\fB\-\-swedish\fP	\fB\-\-svenska\fP
\fB\-\-german\fP	\fB\-\-deutsch\fP
\fB\-\-spanish\fP	\fB\-\-español\fP
\fB\-\-portuguese\fP	\fB\-\-português\fP
\fB\-\-french\fP	\fB\-\-français\fP
\fB\-\-russian\fP	\fB\-\-русский\fP
\fB\-\-italian\fP	\fB\-\-italiano\fP
\fB\-\-serbian\fP	\fB\-\-српски\fP
\fB\-\-norwegian\fP	\fB\-\-norsk\fP
\fB\-\-indonesian\fP
\fB\-\-chinese\fP	\fB\-\-中文\fP
\fB\-\-esperanto\fP
\fB\-\-dutch\fP	\fB\-\-nederlands\fP
.TE
.
.SH PRO TIPS
.
.IP \(bu 2n
If you build a package and then choose not to install it, the built package
file will still be moved to the cache. You can then install it whenever you
want with \fI\-C\fR.
.
.IP \(bu 2n
Research packages using \fI\-Ad\fR, \fI\-Ai\fR, and \fI\-Ap\fR!
.
.IP \(bu 2n
When upgrading, use \fI\-Akua\fR instead of just \fI\-Au\fR.  This will
remove make deps, as well as show PKGBUILD diffs before building.
.
.SH SEE ALSO
.
\fBaura.conf(5)\fR, \fBpacman\fR(8), \fBpacman.conf\fR(5), \fBmakepkg\fR(8)
.
.SH BUGS
.
It is not recommended to install non-AUR packages with pacman or aura. Aura will
assume they are AUR packages during a \fI\-Au\fR and attempt to upgrade them. If
a name collision occurs (that is, if there is a legitimate AUR package with the
same name as the one you installed) previous installations could be overwritten.
.
.SH AUTHOR
.
Colin Woodbury <colin@fosskers.ca>
.
.SH CONTRIBUTORS
.
.TS \" Tab-separated
l .
Chris Warrick
Brayden Banks
Denis Kasak
Edwin Marshall
Jimmy Brisson
Kyle Raftogianis
Nicholas Clarke
.TE
.
.SH TRANSLATORS
.
.TS \" Tab-separated
c l .
Polish	Chris Warrick and Michał Kurek
Croatian	Denis Kasak and "stranac"
Swedish	Fredrik Haikarainen and Daniel Beecham
German	Lukas Niederbremer
Spanish	Alejandro Gómez, Sergio Conde, and Max Ferrer
Portuguese	Henry Kupty, Thiago Perrotta, and Wagner Amaral
French	Ma Jiehong and Fabien Dubosson
Russian	Kyrylo Silin and Alexey Kotlyarov
Italian	Bob Valantin and Cristian Tentella
Serbian	Filip Brcic
Norwegian	"chinatsun"
Indonesian	"pak tua Greg"
Chinese	Kai Zhang
Japanese	Onoue Takuro
Esperanto	Zachary Matthews
Dutch	Joris Blanken
Turkish	Cihan Alkan
.TE
